### PR TITLE
Add UN official country names

### PR DESCRIPTION
**Pull request by briatte**
Adds support for conversion from/to official UN country names in all six official UN languages.

Sources:
- http://www.un.org/en/members/
- http://www.un.org/fr/members/
- http://www.un.org/es/members/
- http://www.un.org/ru/members/
- http://www.un.org/zh/members/
- http://www.un.org/ar/members/

Official list:
- http://unstats.un.org/unsd/geoinfo/UNGEGN/wg1.html
- http://unstats.un.org/unsd/geoinfo/UNGEGN/docs/10th-uncsgn-docs/econf/E_CONF.101_25_UNGEGN%20WG%20Country%20Names%20Document.pdf

Notes:
- The PR adds a dependency to R >= 2.1.0 due to UTF-8 strings.
- R CMD CHECK now throws in a NOTE to signal the presence of non-ASCII strings.
- The script used to append the data is included and named `prep_un.r`.

Further suggestions:
- Add localized regexes for at least French and Spanish?
- Support passing any dataset as the source of the codes?

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
@briatte I had disabled github notifications during crunchtime at work, and completely missed this. What an awesome contribution! Sorry for the delay!

After looking at the code, I realized that the UN had changed their webpage, and that your code no longer worked. So I re-wrote a really simple function to download the country names (merging on flag name). You can look at the short code here: https://github.com/vincentarelbundock/countrycode/blob/master/utilities/un_country_names.R

This commit integrates all official languages as destination codes: https://github.com/vincentarelbundock/countrycode/commit/6ad95c122f42d1af3f9994486f1e3e6238943abe

And thanks to @sumtxt, we also have German regexes for origin.

Let me know if this works for you, and sorry again for the delay.

I hope to push to CRAN in the coming days.

**Comment by briatte** [comment]
That works for me. I submitted the code some time ago and cannot remember the details, but if the idea of having UN official names in the package works for you, I'm happy. Just expect the UN preparation code to break now and then…

**Related note** – Back in March, I also worked on French regexes, but never finished. See [this Gist](https://gist.github.com/briatte/0b31171a56b8e00c2b5b488ca57b3ec3), which contains the draft regex CSV and a draft PR text. Let me know if you want me to get back to the code and finish the regexes.


.

**Comment by vincentarelbundock** [comment]
Évidemment, ce serait une addition très (!) utile, mais j'hésite à faire une demande comme celle-là puisque je sais que préparer des regex est long et difficile...

**Comment by briatte** [comment]
My favourite French geopolitics specialist [just died](https://politbistro.hypotheses.org/4018), so I might just finish my draft regexes as a kind of tribute.

**Comment by vincentarelbundock** [comment]
Well that's too bad. Anything I should read from him? I'm ashamed to say I don't know him, even thought this is kind of my field (coming from an American tradition, however).

**Comment by briatte** [comment]
Don't worry about not knowing him, he wasn't an academic _per se_ – he ran his own private lab, producing a [fantastic show about geopolitics](http://ddc.arte.tv/) on Franco-German TV channel Arte. Check the videos on Youtube ("Le dessous des cartes") if you understand either French or German!

**Comment by vincentarelbundock** [comment]
looks cool, will definitely check it out.

**Pull request closed without merging**
