### PR TITLE
update GENC scraper

### PR DESCRIPTION
**Pull request by cjyetman**
CAUTION: this does cause 2 deletions and numerous additions to the CSV data

### CODE REVIEW

**Comment by cjyetman** [comment]
@vincentarelbundock this removes "WESTERN SAHARA" and "BONAIRE, SINT EUSTATIUS, AND SABA", which I believe is correct (i.e. they don't appear to be included in GENC, Edition 3.0, Update 17 as of 30 June 2022).

But it also adds a bunch of territories... would you prefer to use a [`not_countries` type list to filter them out](https://github.com/vincentarelbundock/countrycode/blob/afb025b1654b0104819e7b305b9d314e96ba5043/dictionary/get_world_bank.R#L8), or is it ok to leave them in the archived GENC data because they won't get merged into the codelist when you run [build.R](https://github.com/vincentarelbundock/countrycode/blob/main/dictionary/build.R) anyway?

**Comment by vincentarelbundock** [comment]
Probably fine to leave them in, no?

**Comment by cjyetman** [comment]
I think so, but I don't ever use the build.R script, so not 100% sure of the expectations there.

**Comment by vincentarelbundock** [comment]
@cjyetman I had to make minor adjustements to `get_genc.R` because calling `CountryToRegex(genc$country)` in the build script generated some missing values and duplicates. Not a big deal at all. Just an FYI.

Dictionary should be updated now on Github.

Do we need a release?

**Comment by cjyetman** [comment]
> Do we need a release?

The past few merges are mostly inconsequential if at all, from a user perspective. #347 is a more important fix that would more reasonably warrant a release.

**Pull request merged**
