### PR TITLE
Added support for German country names. 

### PR DESCRIPTION
**Pull request by sumtxt**

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
This looks great. Especially the regex. Thanks! 

On holiday now, but will look into this as soon as I get a chance.

**Comment by cjyetman** [comment]
May I suggest that you make the CSV file comma delimited instead of semi-colon delimited so that, for instance, read.csv() (as in prep.R) works with its default parameters.

**Comment by cjyetman** [comment]
Also, given that this adds the first alternate regex origin, it may be a good time to implement #68 rather than the very specific switch implemented here.

**Comment by cjyetman** [comment]
and you should add 'German country names' to the list of coding schemes in `@note`

**Comment by vincentarelbundock** [comment]
I'm working on a solution to integrate this PR and https://github.com/vincentarelbundock/countrycode/pull/64 at the same time.

**Comment by sumtxt** [comment]
@vincentarelbundock: Sounds good! The design idea of @cjyetman for #68 would simplifies things for external contributors a lot. +1 Initially I wanted to submit a custom dictionary only but then noticed that I can't have regex in there.

**Comment by vincentarelbundock** [comment]
@sumtxt I think https://github.com/vincentarelbundock/countrycode/commit/6ad95c122f42d1af3f9994486f1e3e6238943abe fixes this issue. Thanks again for the German regexes; this is really awesome!

Also, would you mind testing a few things to see if the current Github version meets your needs? Thanks!

**Comment by sumtxt** [comment]
@vincentarelbundock I just installed the new version and it works with my previous code. I haven't done extensive testing, but for two separate datasets I got the same matches. Let me know if you want me to look into something in particular. One design issue: I would encourage you to include a running id variable in the countrycode_data.rda. This makes it easier for contributors to merge in their data. From the outside it is not immediately clear that country.name.en uniquely identifies all observations. The new warning msg for unmatched/multiple matches is great. +1

**Comment by vincentarelbundock** [comment]
Thanks a lot for looking into this. And thanks again for your contribution.

Yeah, I've thought about a unique identifier, but so far haven't gotten around to doing it. I don't have a good reason; just the vague feeling that the package was motivated by my hatred of competing standards, and that creating a new one felt distasteful :)

**Comment by sumtxt** [comment]
You are welcome! 

Clarification about the ID: I didn't mean to suggest to have yet another 'new countrycode'. A simple running id variable from 1 to K (or a hash / random sequence) would be sufficient.

**Comment by vincentarelbundock** [comment]
yeah, yeah, I know. Just highlighting the sources of my irrational fear of new identifiers (even if 1:N).

**Pull request closed without merging**
