### PR TITLE
fixed ICAO regions

### PR DESCRIPTION
**Pull request by espinielli**
In the past I did incorrectly encode ICAO regions.
This commit fixes the ICAO regions according to https://cfapp.icao.int/MET/MET_LocIndicRegion.aspx

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
Thanks for this. However, it seems like this commit also alters other things.

For instance, you have removed the last line of the file (ZWE), which drops this country from the package altogether. Given the large number of changes in your commit, it is difficult to audit it and to make sure if there hasn't been other problems introduced.

Would it be possible for you to simply add a file called `dictionary/data_icao_region.csv` with just two columns: icao_country_name, icao_region. I'm actually not asking for regexes in the first column, just the raw country names as shown on the icao website.

I know this is more work for you, but it would greatly faciltate this on my en.

**Comment by espinielli** [comment]
Well spotted, `ZWE` is not intentional and in fact an error on my part.
Please discard this PR and I will submit another one with the `dictionary/data_icao_region.csv` as requested

**Comment by espinielli** [comment]
Ooops. It is not so easy.
For example the USA are part in ASIAPAC (Alaska ICAO codes PA, PF, PO, PP), part in NAM (contiguous States)...
There is a unique mapping from Two-Letter_ICAO-State-code to Region but not from Country name...
What would you suggest?

**Comment by vincentarelbundock** [comment]
Right now, countrycode only allows one-to-one mapping. This is a longstanding issue, and I've explored solutions, but none are easy, and none are likely to be implemented in the short run.

In the meantime, I suggest you save a CSV which can include a many-to-one mapping, but also tell me which ones we should (abitrarily) drop out to preserve one-to-oneness.

**Comment by espinielli** [comment]
I am adding the CSV file as you suggested where I map USA to NAM|ASIAPAC.
I'll drop a commit soon

**Comment by vincentarelbundock** [comment]
Great. I'd need all previous commits eliminated though. I'm going to build a script around that CSV, with no change to static data. Maybe it's best to just start a new PR with JUST the csv file.

**Comment by espinielli** [comment]
restarted from scratch, please discard this PR a new one coming

**Comment by cjyetman** [comment]
Not to be contrary, but... is it "correct" to create a synthesized area code for the USA? So USA will be in a nonexistent region of its own?

**Comment by vincentarelbundock** [comment]
oh, I thought there was one for the USA, and then more for subnational units. I don't think we should create a new code. Should be NA in that case.

**Comment by vincentarelbundock** [comment]
Thanks for your patience! https://github.com/vincentarelbundock/countrycode/commit/ae1565293ca3ad98485d58e75a13a9daf9f08ee3

**Comment by espinielli** [comment]
You are welcome.

PS: it is @espinielli but it does not matter 😀

**Comment by vincentarelbundock** [comment]
oops, got it! https://github.com/vincentarelbundock/countrycode/commit/0783e0a3747e822553e8497337ee553cd9d9b324

**Pull request closed without merging**
