### PR TITLE
Handle whitespaces in Ireland country name regex

### PR DESCRIPTION
**Pull request by etpinard**
as suggested in https://github.com/vincentarelbundock/countrycode/pull/134#issuecomment-280270377

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
Thanks for sticking with us to address this!

Unfortunately, we'll need to modify this new regex eventually anyway, because it produces ambiguous results when "Ireland" is surrounded by non-space characters. For instance,

```
> library(countrycode)
> countrycode('The Government of Ireland has announced', 'country.name', 'country.name')
[1] NA
Warning message:
In countrycode("The Government of Ireland has announced", "country.name",  :
  Some values were not matched unambiguously: The Government of Ireland has announced

> countrycode('  Ireland  ', 'country.name', 'country.name')
[1] "Ireland"
> 
```

**Comment by vincentarelbundock** [comment]
The new regex fails this test: https://github.com/vincentarelbundock/countrycode/blob/master/tests/testthat/test-regex-sentence.R

**Comment by cjyetman** [comment]
That's partially my fault... I said that it should ignore leading and trailing white space, but technically we're going for even more than that.

**Comment by vincentarelbundock** [comment]
This regex `^(?!.*north).*\bireland ` does not use a lookbehind (i.e., javascript compatible), and it picks up those two instances:

```
I heard that Ireland is beautiful
    Ireland   
``` 

I doesn't cause conflict when we feed it "Kingdom of Great Britain and Northern Ireland"

1636c18 thus solves the issue (permanently?). Closing.

**Comment by vincentarelbundock** [comment]
Thanks again for the report and for the help!

**Pull request closed without merging**
