### PR TITLE
Tweak `countrycode()` documentation

### PR DESCRIPTION
**Pull request by salim-b**

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
Thanks!

Do we know why tests are failing?

**Comment by salim-b** [comment]
> Do we know why tests are failing?

No clue, they only fail on obsolete R versions (< 3.6) with the following error:

```
Error in gsub("\r\n", "\n", str, fixed = TRUE) : 
  input string 1 is invalid in this locale
Calls: <Anonymous> -> new_rcmdcheck -> win2unix -> gsub
```

So the error occurs in [`rcmdcheck:::win2unix()`](https://github.com/r-lib/rcmdcheck/blob/fe512fb7ba7c80ca8b21651aa79d9df0bf73ab14/R/utils.R#L6-L8). [This loosely related SO answer](https://stackoverflow.com/a/46392502/7196903) seems to indicate it might have to do with some strange locale issue.

**Comment by vincentarelbundock** [comment]
Thanks for looking into this. FWIW, I pushed a minor commit rolling back your change to DESCRIPTION, and rebuilding the docs with the release verision of Roxygen, and the results were the same.

I'm annoyed by this, because I like that we support old versions (not "obsolete"!). But my guess is that this is probably not a big problem and that this is more to do with the testing tooling chain than with the actual functionality of the package. 

Still need to investigate.

**Comment by vincentarelbundock** [comment]
Good news! The tests on the repo seem to have magically sorted themselves out. Why? Who knows!

But I filed a bug report on the `rcmdcheck` repository and the maintainer thinks this is actually a bug on their end. So think we can stop worrying about this for now.

**Comment by NilsEnevoldsen** [comment]
https://github.com/r-lib/rcmdcheck/issues/140

**Pull request merged**
