### PR TITLE
added support for Gleditsch & Ward (character and numeric) codes

### PR DESCRIPTION
**Pull request by altaf-ali**

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
@altaf-ali

Thanks for th PR? This looks really nice and complete!

I've nerves used these codes. Is there any similarity with an existing scheme, like polity for Example?

I'm on vacation without a computer right now, but I'll look at this when I come back,

**Comment by vincentarelbundock** [comment]
! Not ?

**Comment by altaf-ali** [comment]
@vincentarelbundock Thanks for the quick response. It's very similar to the COW scheme but a number of datasets (UCDP, PRIO, etc) use GW and it's widely used in conflict research. Most poli-sci people end up writing their own conversion routines so having it in countrycode would be helpful.

**Comment by vincentarelbundock** [comment]
Sounds like a no brainer. Thanks!

**Comment by cjyetman** [comment]
Would it be too much trouble to remove all the whitespace-only changes in the PR? It just makes it a bit harder to review.

**Comment by cjyetman** [comment]
and [NEWS ](https://github.com/vincentarelbundock/countrycode/blob/master/NEWS) probably should be updated? Or do you prefer to do that @vincentarelbundock?

**Comment by vincentarelbundock** [comment]
Also, wondering if this dataset (and their microstates datasets) wouldn't be a better starting point for the panel codelist.

**Comment by altaf-ali** [comment]
Just fixed whitespaces (and a bug in get_gw.R). I'm not in a rush, so don't mind waiting.

**Comment by vincentarelbundock** [comment]
Looks like Gleditsch's site is down...

**Comment by vincentarelbundock** [comment]
@altaf-ali Thanks so much for putting this together. A great addition!

And sorry for taking so long; summer's been a bit crazy.

I had to make a couple other commits to build the data dictionary, so I'm closing this regex with this commit: https://github.com/vincentarelbundock/countrycode/commit/caead7c4b39864a2b9c79f80c1eedef1bd6a13e6

The new functionality works on my local machine, and all tests pass, but I'd still be grateful if you could give it a shot on your end as well.

Cheers!

**Pull request closed without merging**
